---
cog_bundle_version: 4
name: net-utils
description: "Simple network utilities"
author: "Dave Long <dlong@cagedata.com>"
homepage: "https://github.com/cogcmd/net"
version: "1.0.0"
docker:
  image: "davejlong/cog-net"
  tag: "1.0.0"
commands:
  dig:
    executable: "/bundle/dig.sh"
    description: "DNS lookup utility"
    long_description: |
      Simple wrapper for the `dig` command line utility. Only a select
      few options are exposed in this command; it is not intended to
      be a complete "dig in chat" tool.
    arguments: "<target>"
    rules:
      - allow
    options:
      short:
        description: "Return a terse answer. Verbose reply is the default"
        type: bool
        required: false
      type:
        description: "Valid BIND 9 query type. Defaults to 'A'"
        type: string
        required: false
      server:
        description: "Name server to query"
        type: string
        required: false
      trace:
        description: "Enable the 'trace' query option. Disabled by default"
        type: bool
        required: false
  whois:
    executable: "/bundle/whois.sh"
    description: "Whois query utility"
    long_description: |
      Simple wrapper for the `whois` command line utility.
    arguments: "<domain>"
    rules:
      - allow
    options:
      server:
        description: "Whois server to query against."
        type: string
        required: false
      port:
        description: "Port on whois server"
        type: string
        required: false
      short:
        description: "Returns a terse answer only containing contact information"
        type: bool
        required: false
  ping:
    executable: "/bundle/ping.sh"
    description: "PING utility"
    long_description: |
      Simple wrapper for the `ping` command line utility. Only a select
      few options are exposed in this command; it is not intended to
      be a complete "ping in chat" tool.
    arguments: "<target>"
    rules:
      - allow
    options:
      count:
        description: "Number of times to ping.  Defaults to 5"
        type: string
        required: false
  nslookup:
    executable: "/bundle/nslookup.sh"
    description: "Query internet name servers interactively"
    long_description: |
      Simple wrapper for the `nslookup` command line utility.
    arguments: "<target>"
    rules:
      - allow
    options:
      server:
        description: "The server to use as source for nslookup."
        type: string
        required: false
  isup:
    executable: "/bundle/isup.sh"
    description: "Check if a website is up or not"
    arguments: "<target>"
    rules:
      - allow
templates:
  net:
    body: |
      ~each var=$results~
      ```
      ~each var=$item.body as=l~
      ~$l~
      ~end~
      ```
      ~end~
  isup:
    body: |
      ~each var=$results~
      ~if cond=$item.status_code == 1~
      ~$item.domain~ is up
      ~end~
      ~if cond=$item.status_code == 2~
      ~$item.domain~ is down
      ~end~
      ~if cond=$item.status_code == 3~
      ~$item.domain~ is invalid
      ~end~
      ~end~
